version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-spring-boot
    environment:
      POSTGRES_USER: sanal
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demodb
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
